query pageQuery {
    ...LayoutQueryFragment
    postConnection {
        edges {
            node {
                id
                date
                title
                excerpt
                author {
                    ... on Author {
                        ...AuthorParts
                    }
                }
                _sys {
                    filename
                }
            }
        }
    }

    noteConnection {
        edges {
            node {
                id
                date
                title
                link
                keywords

                _sys {
                    filename
                }
            }
        }
    }
}

query contentQuery($relativePath: String!) {
    ...LayoutQueryFragment
    page(relativePath: $relativePath) {
        ...PageParts
    }
}

query blogPostQuery($relativePath: String!) {
    ...LayoutQueryFragment
    post(relativePath: $relativePath) {
        ...PostParts
        author {
            ... on Author {
                name
                avatar
            }
        }
    }
}

query noteQuery($relativePath: String!) {
    ...LayoutQueryFragment
    note(relativePath: $relativePath) {
        ...NoteParts
    }
}
